services:
  webshop_db:
    build: ./database/
    ports: 
      - '3306'
    volumes: 
      - webshop-mysql-data:/var/lib/mysql
    env_file: 
      - ./database/.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USERNAME: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "${MYSQL_ROOT_USERNAME}", "--password=${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 5
  webshopbackend:
    build: ./backend/webshop
    ports:
      - '9000'
    env_file:
      - ./backend/webshop/.env
    depends_on:
      webshop_db:
        condition: service_healthy
  webshopfrontend:
    build: ./frontend/webshop-app/
    ports:
      - '3000:8080' 
    depends_on:
      - 'webshopbackend'
 
      
volumes:
  webshop-mysql-data:
       